name: "Provisioning Infrastructure"

on:
  push:
    branches: ["master","dev","stage"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Extract brach name
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
      id: extract_branch  

    - name: Chekout code
      uses: actions/checkout@v2
      with:
        ref: ${{steps.extract_branch.outputs.branch}}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # role-to-assume: ${{secrets.AWS_ROLE}}
        # role-session-name: Github-Actions
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


        
    - name: Install Terraform 
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 1.3.9
        terraform_wrapper: false
      
    - name: Initialize Terraform 
      run: |
        terraform init
    
    - name: Terraform Select Workspace
      run: |
        echo $( [ "${{steps.extract_branch.outputs.branch}}" == "master" ] && echo "prod" || [ "${{steps.extract_branch.outputs.branch}}" == "stage" ] && echo "stage" || [ "${{steps.extract_branch.outputs.branch}}" == "dev" ] && echo "dev" )
    
    - name: Terraform Plan 
      run: |
        terraform plan -input=false